### ISSUE TITLE
Citing enterprise_extensions

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/enterprise_extensions#119]
What is the preferred way of citing this package in a paper? Is there an official bibtex entry? 
Thanks.

**Comment by paulthebaker** [comment]
As of now, there is no official citation.  It is cited in the [NANOGrav 12.5yr stochastic background analysis paper](https://arxiv.org/pdf/2009.04496.pdf) as:

```
Taylor, S. R., Baker, P. T., Hazboun, J. S., Simon, J. J., & Vigeland, S. J. 2018, enterprise extensions.
https://github.com/nanograv/enterprise extensions
```

We should make a zenodo and put a bibtex block in the README.
