### ISSUE TITLE
New Version for NG15-year Analyses

### ISSUE THREAD

**Issue by Hazboun6** [nanograv/enterprise_extensions#132]
With the merging of a few PRs recently (#127, #128, #130 ) we should version and tag the code base once again. Is there anything else we should include before doing so? It seems like #129 should also be included. 

Also given the PRs listed above, should we jump the minor version number or just say this is a small update, i.e. v2.1.1 or v2.2.0? Or something else?

**Comment by paulthebaker** [comment]
Following the [semantic versioning](https://semver.org/) convention, backwards compatible new functionality implies a minor version update.  So we should go to `v2.2.0`.

In general we should be better about bumping the "patch" version number more often.

**Comment by Hazboun6** [comment]
This Issue was completed with #134
