### ISSUE TITLE
hypermodel issue with using save.runtime.info function

### ISSUE THREAD

**Issue by ddegan4** [nanograv/enterprise_extensions#142]
OS and version: Ubuntu 18.04.5

Bug Details:
In trying to use hypermodel.py once the HyperModel is created the setup_sampler() call returns an error saying "'HyperModel' object has no attribute 'summary'". This comes from the save.runtime.info function within the setup_sampler function. The full error output is shown below.

<img width="1075" alt="Screen Shot 2021-10-03 at 1 26 19 PM" src="https://user-images.githubusercontent.com/91853886/135773787-48529d11-a31e-4b77-bb2a-8813583be427.png">

**Comment by paulthebaker** [comment]
It's better to copy/paste error messages instead of screenshotting them.

You can get syntax highlighting in markdown by using three backticks for block code and tagging with the language, e.g.:
```python
AttributeError: 'HyperModel' object has no attribute 'summary'
```

**Comment by Hazboun6** [comment]
@paulthebaker Do you have a fix underway already?
