### ISSUE TITLE
inappropriate cov.npy still loaded by HyperModel.setup_sampler

### ISSUE THREAD

**Issue by kdolum** [nanograv/enterprise_extensions#182]
Issue #174 reported loading of old cov.npy even when resume=False in setup_sampler in sampler.py, and it was fixed in PR #175.  The same problem exists in setup_sampler in hypermodel.py.  Pending some future elimination of duplicate code, the fix should presumably be copied to the other function.

**Comment by paulthebaker** [comment]
@AaronDJohnson since you made the PR #175, can you duplicate the changes to `hypermodel.py`?  If not, I can get to it at the end of the week.
