### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by Ypatel1swat** [nanograv/enterprise_extensions#211]
Hello everyone,

I have just installed enterprise and enterprise_extensions and am running the standard GWB analysis. I can across this error:

```
`File "/home/ypatel1/PTA/ng15yr_std_analysis.py", line 53, in <module>
    sampler = super_model.setup_sampler(resume=resume, outdir=outdir, sample_nmodel=False)
  File "/home/ypatel1/anaconda3/envs/ent15y/lib/python3.9/site-packages/enterprise_extensions/hypermodel.py", line 190, in setup_sampler
    groups = self.get_parameter_groups()
  File "/home/ypatel1/anaconda3/envs/ent15y/lib/python3.9/site-packages/enterprise_extensions/hypermodel.py", line 118, in get_parameter_groups
    list(np.unique(groups))
  File "/home/ypatel1/anaconda3/envs/ent15y/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 272, in unique
    ar = np.asanyarray(ar)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (69,) + inhomogeneous part.`
```

Upon searching, [this](https://stackoverflow.com/questions/67183501/setting-an-array-element-with-a-sequence-requested-array-has-an-inhomogeneous-sh) stackoverflow suggested downgrading numpy to version 1.21.6 (I originally had version 1.25.0) which seems to have solved the error.

**Comment by AaronDJohnson** [comment]
I will look into this after the 30th. I thought that v2.4.2 should have fixed this issue. Can you tell me which version of enterprise_extensions you have and how you installed it?

**Comment by Ypatel1swat** [comment]
Oh I see, I am using v2.4.0. I will update my enterprise_extensions and post the results

**Comment by Ypatel1swat** [comment]
I updated my version of enterprise_extensions and it seems to work with version 1.25.0 of numpy

**Comment by AaronDJohnson** [comment]
Thanks @Ypatel1swat , I'm closing this as resolved.
