### ISSUE TITLE
errors for install this packages

### ISSUE THREAD

**Issue by CloudduolC** [nanograv/enterprise_extensions#239]
Collecting git+https://github.com/nanograv/enterprise_extensions@master
  Cloning https://github.com/nanograv/enterprise_extensions (to revision master) to c:\users\w10\appdata\local\temp\pip-req-build-gp5eb6u0
  Running command git clone --filter=blob:none --quiet https://github.com/nanograv/enterprise_extensions 'C:\Users\w10\AppData\Local\Temp\pip-req-build-gp5eb6u0'
  Resolved https://github.com/nanograv/enterprise_extensions to commit d91baf26d1d8d85b25bebaea108ceebc474c3896
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.16.3 in d:\install_softwares\python\lib\site-packages (from enterprise_extensions==2.4.3) (2.0.1)
Requirement already satisfied: scipy>=1.2.0 in d:\install_softwares\python\lib\site-packages (from enterprise_extensions==2.4.3) (1.14.0)
Collecting ephem>=3.7.6.0 (from enterprise_extensions==2.4.3)
  Using cached ephem-4.1.5-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Collecting healpy>=1.14.0 (from enterprise_extensions==2.4.3)
  Using cached healpy-1.17.3.tar.gz (4.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scikit-sparse>=0.4.5 (from enterprise_extensions==2.4.3)
  Using cached scikit_sparse-0.4.15.tar.gz (214 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pint-pulsar>=0.8.2 (from enterprise_extensions==2.4.3)
  Using cached pint_pulsar-1.0.1-py3-none-any.whl.metadata (7.4 kB)
Collecting libstempo>=2.4.0 (from enterprise_extensions==2.4.3)
  Using cached libstempo-2.5.0.tar.gz (965 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "D:\install_softwares\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\install_softwares\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\install_softwares\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\w10\AppData\Local\Temp\pip-build-env-89uurgzp\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\w10\AppData\Local\Temp\pip-build-env-89uurgzp\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\w10\AppData\Local\Temp\pip-build-env-89uurgzp\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 60, in <module>
        File "<string>", line 23, in _get_tempo2_install_location
        File "D:\install_softwares\python\Lib\pathlib.py", line 1162, in __init__
          super().__init__(*args)
        File "D:\install_softwares\python\Lib\pathlib.py", line 373, in __init__
          raise TypeError(
      TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
how to fix it?

**Comment by AaronDJohnson** [comment]
Hi @CloudduolC , this error is caused because of a failure to install `libstempo`. Are you using an M-series Mac?

**Comment by CloudduolC** [comment]
Sorry, I am using the Windows operating system now. May you provide some feasible ways to use these corresponding packages on windows?  Any kind assistance would be appreciated very much.

**Comment by AaronDJohnson** [comment]
> Sorry, I am using the Windows operating system now. May you provide some feasible ways to use these corresponding packages on windows? Any kind assistance would be appreciated very much.

Using WSL (Windows Subsystem for Linux) can help you in this case. `libstempo` installs without issue for many of the Linux distributions that are supported by WSL. An alternative is to install some sort of virtual machine with a linux distribution and use that.

**Comment by AaronDJohnson** [comment]
Closed due to inactivity. Please open another issue if your problem persists.
