### ISSUE TITLE
No versioning

### ISSUE THREAD

**Issue by bshapiroalbert** [nanograv/enterprise_extensions#65]
As far as I can tell, there is no versioning within `enterprise_extensions`. Some type of versioning should be added soon so that we can report the version of all software used to create and analyze the NANOGrav datasets for reproducibility purposes.

**Comment by Hazboun6** [comment]
This is an important Issue that will need to be addressed for the NANOGrav dataset production and gravitational wave analyses. @swiggumj I know that there is still some development happening in the timing analysis suite, as well as `Pint`. What timeline/deadline should I be looking at when trying to get `e_e` versioned?

**Comment by swiggumj** [comment]
Good question...will hopefully have an answer shortly.

**Comment by swiggumj** [comment]
Probably good to do it after #90 is merged. Though I suppose it's possible we'll iterate a bit more after that, but if so, that could easily be captured in a minor revision.

**Comment by svigeland** [comment]
@stevertaylor and I have discussed formally freezing the code for the 15yr GWB analysis, and we came up with a deadline of August 1 for doing this. In terms of versioning enterprise_extensions, I think we want to do this before we institute this code freeze, which means that we can set versioning enterprise as a goal for the summer.

**Comment by Hazboun6** [comment]
Thanks for the input. So I suppose this means that we will end up with a version that is used in the data release and a version that is used in the DWG analysis, but I think that will be true of `enterprise` as well.

**Comment by svigeland** [comment]
@Hazboun6, it's possible that we could use the same version for the data release and the GWB analysis, but I think it's likely that we will find new things that we want to add to enterprise and/or enterprise_extensions while doing our exploratory analyses. That's why @stevertaylor and I put down August 1 as the deadline to freeze the code.

**Comment by paulthebaker** [comment]
This was fixed in #96.
