### ISSUE TITLE
model_general is broken due to new multiple orfs

### ISSUE THREAD

**Issue by NihanPol** [nanograv/enterprise_extensions#86]
`orf = None`, the default option, does not work due to the new loop:
`for elem in orf.split(','):
        crn.append(common_red_noise_block(psd=common_psd, prior=amp_prior_common, Tspan=Tspan,
                                          components=common_components, gamma_val=gamma_common,
                                          delta_val=None, orf=elem, name='gw_{}'.format(elem),
                                          coefficients=coefficients, pshift=pshift, pseed=None))`

A fix will be to change the default to `orf = "None"

**Comment by NihanPol** [comment]
Also, `orf = None` is no longer recognized by `common_red_noise` in `blocks.py`. Recommend changing default in `model_general` to `orf = "crn,"`.

**Comment by stevertaylor** [comment]
`orf=None` should be recognized by `common_red_noise` in `blocks.py`. There is a specific `if` statement to catch that.

**Comment by stevertaylor** [comment]
I agree that the default for `orf` in `model_general` should be `crn`. I can make that edit now.

**Comment by stevertaylor** [comment]
Could you check https://github.com/nanograv/enterprise_extensions/pull/88 to confirm that it fixes the issue?

**Comment by NihanPol** [comment]
Yes that fixes the problem! Thank you!
