### ISSUE TITLE
New `model_general` incompatible with current version of `optimal_statistic.py`.

### ISSUE THREAD

**Issue by NihanPol** [nanograv/enterprise_extensions#87]
In the new version of `model_general.py`, the name of the GW signal is set as `"gw_{}".format(elem)` (line 727), which then gets propagated through to GP signals and sets the ID of the signal by the same name.
`optimal_statistic.py` meanwhile searches for the GW signal by doing (line 249) `if sig.signal_name == 'red noise' and sig.signal_id == 'gw':`, which is no longer satisfied since the GW signal is now called `gw_*`. This leads to the following error:
```
Traceback (most recent call last):
  File "model_general_ipta_optstat.py", line 156, in <module>
    optstat = optimal_statistic.OptimalStatistic(psrs, pta=pta, bayesephem=args.useBE, orf = args.orf)
  File "/home/polns/.conda/envs/pta_software/lib/python3.8/site-packages/enterprise_extensions/frequentist/optimal_statistic.py", line 57, in __init__
    self.freqs = self._get_freqs(psrs)
  File "/home/polns/.conda/envs/pta_software/lib/python3.8/site-packages/enterprise_extensions/frequentist/optimal_statistic.py", line 253, in _get_freqs
    return freqs
UnboundLocalError: local variable 'freqs' referenced before assignment
```

**Comment by NihanPol** [comment]
My fix for this problem is below. Will try to submit a pull request later this week.

Change the following lines in `optimal_statistic.py` to the one given here:
line 239: `if signal.signal_name == 'red noise' and 'gw' in signal.signal_id:`
line 249: `if signal.signal_name == 'red noise' and 'gw' in signal.signal_id:`

**Comment by Hazboun6** [comment]
@NihanPol has this been addressed in a given PR yet?

**Comment by stevertaylor** [comment]
@NihanPol , checking again. If this is no longer an issue can you please close?

**Comment by NihanPol** [comment]
Fixed in recent updates to e_e. Closing issue.
